name = "ligo-space"
main = "src/index.js"
compatibility_date = "2026-09-01"

# Un-comment and update these routes once your custom domain is on Cloudflare DNS
# routes = [{ pattern = "ligospace.co.ke/api/*", zone_name = "ligospace.co.ke" }]

[[d1_databases]]
binding = "DB"
database_name = "ligo"
database_id = "6d6e177a-37b9-4c8d-9b19-fc50dbcc2642"

[ai]
binding = "AI"

[vars]
SUPABASE_URL = "https://lpnnntuelgaisoiimuka.supabase.co"
SITE_URL = "https://ligo-space.ligospace-ke.workers.dev/" # Update to https://ligospace.co.ke once domain is live
SIGNUP = "invite"                           # Set to "open" when ready for open registration
FROM_EMAIL = "onboarding@resend.dev"
